### ISSUE TITLE
"Ensuring Chocolatey Is Installed" behind a NAT triggers chocolatey.org's rate limit

### ISSUE THREAD

**Issue by timothy-mcroy** [OctopusDeploy/Library#953] opened 2020-07-08 21:34 UTC
### Step template
_Chocolatey - Ensure Installed_

### Step template parameter inputs
_Not applicable_

### Step template version
_Latest_

### Step template related environment information
_Windows 2016 with 5 or more deployment targets behind the same NAT_

### Octopus Server version
_v2020.1.10_

### Expected behavior

_Chcoolatey should be installed on more than 5 targets without triggering the rate limit on Chocolatey.org_

### Actual behavior

_The rate limit is triggered as the step runs against all targets simultaneously be default_

### Possible solution
First solution would be to allow a custom chocolatey feed location to be specified. The second solution would be to, somehow, ensure this step uses a rolling deployment by default (or no warning if a custom chocolatey feed is specified).  

### Steps to reproduce the problem (for bugs)

This can be reproduced by having 6 deployment targets under the same NAT running the step template.

Relevant documentation on chocolately.org rate limits - https://chocolatey.org/docs/community-packages-disclaimer#rate-limiting

**Comment by pauby** [comment] 2020-08-03 09:37
This isn't an issue for the step template or Octopus. The issue is the [rate limiting](https://chocolatey.org/docs/community-packages-disclaimer#rate-limiting) that Chocolatey.org uses to ensure fair use of the site.

I am have picked up the Chocolatey step templates and I have added a source option (so you can install from your own internal source). These have yet to be pushed but will be very shortly.

**Comment by pauby** [comment] 2020-08-03 09:38
If somebody wants to assign this (if possible) to me that would help?


/cc @DevOpsDerek

**Comment by DevOpsDerek** [comment] 2020-08-03 09:39
Thanks @pauby 👍

**Closed** 2020-08-10 19:28 UTC
