### ISSUE TITLE
windows-scheduled-task-create needs try/catch for permissions

### ISSUE THREAD

**Issue by dragon788** [OctopusDeploy/Library#358] opened 2016-08-18 15:11 UTC
After getting a permissions error, the script continued and thought it had deployed the scheduled task even though that couldn't have been possible.

```
ERROR: Logon failure: the user has not been granted the requested logon type at this computer.
Error    17:00:17
ERROR: The specified task name "Project - sync" does not exist in the system.
Info    17:00:17
Creating Scheduled Task - Project - sync
schtasks.exe /create /ru ServiceAccountUser /rp '********' /tn "Project - sync" /tr "'D:\Octopus\Applications\Production\ProjectSync\0.0.1.44\ProjectSync.exe'" /sc MINUTE   /F /MO 30 
Successfully Created Project - sync
Project - sync enabled
Info    17:00:17
==============================================
PowerShell exit code: 1
==============================================
Fatal    17:00:17
PowerShell script returned a non-zero exit code: 1
Tentacle version 2.6.5.1195
```

**Comment by dragon788** [comment] 2016-08-18 16:33
This is a note to myself that I also need to go back and merge some of the functionality that we've added to our internal copy of this task with the previously published one to handle arguments and weekdays again.

**Comment by dragon788** [comment] 2016-08-18 17:51
Update with build in Validate methods. http://brandonpadgett.com/powershell/Little-Known-V3-Feature/

**Comment by mikeclayton** [comment] 2016-12-01 12:32
Hi.

Any update on pushing your latest commits?

I've just hit a similar issue myself with non-zero exit codes from schtasks.exe being ignored, in my case caused by a bug when using the "WEEKDAYS" schedule type. I've got local fixes for both that I can send a PR for, but I don't do that if you've already fixed them internally.

Cheers,

M

**Comment by dragon788** [comment] 2016-12-01 16:29
I'll see if I can take a look. One of the things I noticed is due to the horrendous mix of metadata and code in the templates, when I updated the file I lost some functionality from the previous version because we had originally installed it to our system from an even earlier version.

**Comment by mikeclayton** [comment] 2016-12-01 17:10
Ok cool, cheers.

If you like, I'll see if I can blend it all together and send a PR for feedback. I need to fix it locally anyway as it's blocking a deployment so i might as well give something back along the way :-).

As an aside, I've also got a couple of "pack.ps1" and "unpack.ps1" scripts that extract the powershell script from the json into a separate file for easier editing and then plop it back again afterwards. That would be massively useful from a contributor perspective as I was struggling with trying to edit it in-place in the json.

Storing it in source as a *.ps1 and a *.json and then packing them together as a CI step would really help. I'll send a separate PR for that as well in case it's any use.

**Comment by dragon788** [comment] 2016-12-01 17:56
Oh that would be fantastic! Please do share, I would love to be able to use AppVeyor to run the pack process and simply store our PowerShell as separate scripts. Since most of the metadata also only pertains to EXACTLY 1 instance of Octopus, I could definitely see the value of merging a dummy template with arbitrarily high numbers that won't affect anybody's local copies as extremely useful. I know @PaulStovell has mentioned they are looking to improve the Library mechanism for Step Templates/etc, but that would make our lives easier while we fight with some internal issues preventing us from updating to Octopus 3.x.

**Comment by matt-richardson** [comment] 2016-12-01 23:00
You guys might be interested in checking out http://mjrichardson.com/blog/continuous-integration-with-octopus-deploy-step-templates/. Does pretty much what you're talking about and adds tests and PSScriptAnalyzer into the mix.

**Comment by dragon788** [comment] 2016-12-02 00:07
@matt-richardson that's awesome, I feel like I've been there before, I just wasn't doing that much with trying to maintain our Octopus instance with code at the time.

**Comment by mikeclayton** [comment] 2016-12-02 13:40
Nice.

I've just sent a PR with a similar subset of tools for packing / unpacking the scripts inside step template files. It's made my life a easier trying to work on the Scheduled Task step template, but I'm happy to remove the PR if it doesn't really add anything to this project.

Cheers,

M

**Comment by mikeclayton** [comment] 2016-12-10 19:32
PR updated as requested.

As an aside, would there any appetite for storing the scripts separately from the templates in this repo, and "packing" them during the CI process? 

Some advantages would be:

+ A lot easier to contribute fixes to templates contributors wouldn't have to care about extracting scripts from the step templates.

+ The history for scripts would be a lot more readable as separate files rather than encoded json on a single line in the step templates.

I can raise a separate issue for this if it's worth discussing.

**Comment by dragon788** [comment] 2016-12-14 21:22
@mikeclayton While I was fiddling with the scripts to get them working I ended up revamping quite a bit to make a "pure PowerShell" script that can also be invoked with `-Debug` or `-Verbose` to get some additional output. I also ended up making it a unified "Converter" script that takes an argument to pack or unpack and defaults to unpacking. This one should be aware of its surroundings and can find the step-templates whether invoked from the Library folder with `.\tools\Converter.ps1` or from within tools with `.\Converter.ps1 -operation pack`.

Converter.ps1
```PowerShell
[CmdletBinding()]
param
(
    [Parameter(Mandatory=$false)]
    [string] $SearchPattern,
    [Parameter(Mandatory=$false)]
    $Operation = 'unpack'
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version "Latest"

$thisScript  = $MyInvocation.MyCommand.Path;
Write-Verbose "`$thisScript $thisScript"
$thisFolder  = Split-Path -parent $thisScript
Write-Verbose "`$thisFolder $thisFolder"
Import-Module -Name (Join-Path $thisFolder "StepTemplatePacker")

$parentFolder = Split-Path -parent $thisFolder
Write-Verbose "`$parentFolder $parentFolder"
$stepTemplateFolder = Join-Path $parentFolder "step-templates"
Write-Verbose "`$stepTemplateFolder $stepTemplateFolder"

if( $PSBoundParameters.ContainsKey("SearchPattern") )
{
    $stepTemplates = Get-ChildItem $stepTemplateFolder -Filter "$SearchPattern.json"
    if (!($stepTemplates)) { "No templates found matching $SearchPattern, maybe try using a wildcard *$SearchPattern*" }
    Write-Debug "$stepTemplates"
}
else
{
    $stepTemplates = Get-ChildItem $stepTemplateFolder -Filter "*.json"
    Write-Debug "$stepTemplates"
}

switch ($Operation)
{
    "unpack" {
    function Run-Command ($stepTemplate)
        {
        write-host "unpacking '$($stepTemplate)'"
        Export-OctopusStepTemplateScripts -StepTemplate $($stepTemplate.FullName) 
        }
        break
    }
    "pack" {
    function Run-Command ($stepTemplate)
        {
        write-host "packing '$($stepTemplate)'"
        Import-OctopusStepTemplateScripts -StepTemplate $($stepTemplate.FullName)
        }
        break
    }
    default {
        Write-Host "No operation parameter detected, assuming 'unpack'"
        Write-Host "Possible -Op arguments are 'unpack' or 'pack'"
        function Run-Command ($stepTemplate)
        {
            write-host "unpacking '$($stepTemplate)'"
            Export-OctopusStepTemplateScripts -StepTemplate $($stepTemplate.FullName) 
        }
     } 
}

foreach( $stepTemplate in $stepTemplates )
{
    Run-Command $stepTemplate
}
```

**Comment by dragon788** [comment] 2016-12-14 21:45
It could be handy to put some checks around unpacking to avoid extracting over top of an existing set of scripts, if you have one you've modified you probably don't want to clobber it, so perhaps some check with whether the currently extracting object reflects an existing extracted script on disk with a confirm overwrite option could be an improvement (eventually).

**Comment by mikeclayton** [comment] 2016-12-15 21:08
@dragon788 - iIve added some more commits and comments over on the pull request ticket. Let me know if there's anything else.

**Comment by mikeclayton** [comment] 2016-12-19 10:07
See below to repro the original issue. I've got a fix which I'll send a PR for tonight...

```
C:\OctopusLibrary> powershell .\tools\_unpack.ps1 windows-scheduled-task-create -force

C:\OctopusLibrary> powershell $OctopusParameters = @{ 'TaskName' = 'myTaskName'; 'RunAsUser' = 'myRunAsUser'; 'RunAsPassword' = 'myRunAsPassword'; 'Command' = 'myCommand.exe'; 'Arguments' = 'myArguments'; 'Schedule' = 'WEEKLY' }; .\step-templates\windows-scheduled-task-create.ScriptBody.ps1

Creating Scheduled Task - myTaskName
schtasks.exe /create /ru myRunAsUser /rp 'myRunAsPassword' /tn "myTaskName" /tr "'myCommand.exe' 'myArguments'" /sc WEEKLY   /F
ERROR: No mapping between account names and security IDs was done.
Successfully Created myTaskName
ERROR: The specified task name "myTaskName" does not exist in the system.
myTaskName enabled

C:\OctopusLibrary> echo %errorlevel%
0
```

**Comment by dragon788** [comment] 2016-12-19 22:27
Nice, the Invoke-CommandLine is pretty slick and a great way to handle the multiple possible calls cleanly.

**Comment by alfhenrik** [comment] 2017-04-11 01:45
Many improvements have been done to this step template that looks to solve this issue so I'm gonna close this now

**Closed by alfhenrik** 2017-04-11 01:45 UTC
